spring:
  application:
    name: electronic-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # 将服务名小写
      routes:
        - id: system-route # system模块的路由id
          uri: lb://system
          predicates:
            - Path=/api/system/**  # 对于指定的路径进行拦截
          filters:
            - StripPrefix=2  # path路径层级过滤，这里面过滤2级，过滤完后，请求根据除了/api/auth/之外进行转发
            
        - id: workflow-route # workflow模块的路由id
          uri: lb://system
          predicates:
            - Path=/api/workflow/**  # 对于指定的路径进行拦截
          filters:
            - StripPrefix=2  # path路径层级过滤，这里面过滤2级，过滤完后，请求根据除了/api/auth/之外进行转发

        - id: attendance-route # workflow模块的路由id
          uri: lb://attendance
          predicates:
            - Path=/api/attendance/**  # 对于指定的路径进行拦截
          filters:
            - StripPrefix=2  # path路径层级过滤，这里面过滤2级，过滤完后，请求根据除了/api/auth/之外进行转发

  #------------------------- redis配置信息--------------------------
  redis:
    host: 10.11.2.67
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: -1
